### ISSUE TITLE
Issue with MakeRoots.R

### ISSUE THREAD

**Issue by rhabel** [pschmidtwalter/LWFBrook90R#21]
Hello, 
I have the impression that there's something wrong with the MakeRoots.R script, or rather the MakeRelRootDens-function. 

```{r LWFBrook90R}
library(LWFBrook90R)
depth <-  slb1_soil$lower
```

``` roots_beta ``` is the standard root density with the default values. (By the way, the first example on the MakeRelRootDens.R - help page has -1,4 instead of -1.4 as maxdepth.)
```{r, eval = T}
roots_beta <- MakeRelRootDens(soilnodes = depth,
                              maxrootdepth = -1.4,
                              beta = 0.97,
                              method = "betamodel")
```
Let's say I'm more interested in the upper layers where I have more measured data for example. So, I create more nodes in the top 15 cm.
```{r, eval = T}
depth.2 <- c(seq(-0.01, -0.15, -0.005), depth[6:22])
roots_beta.2 <- MakeRelRootDens(soilnodes = depth.2,
                                maxrootdepth = -1.4,
                                beta = 0.97,
                                method = "betamodel")

plot(roots_beta, depth, type = 's',
     col = "brown", lwd = 1.5,
     ylab = "soil depth [m]",xlab = "relative root density")
lines(roots_beta.2, depth.2, type = 's',
      col = "red", lwd = 1.5)
```
While they look different, the sum of the relative cumulative function has to be one and it is for both roots_beta and roots_beta.2 (```sum(roots_beta); sum(roots_beta.2)``` are both 1), but there are some logical issues...

For example the cumulative sum in 16 cm depth is 

```cumsum(roots_beta)[which(depth == -0.16)]``` = 0.6660798, or 66%
```cumsum(roots_beta.2)[which(depth.2 == -0.16)]``` = 0.9042575, over 90%

Or the depth at which 80% of roots are found would be 
```depth[which(cumsum(roots_beta) >0.80)[1]]``` = -0.28
```depth.2[which(cumsum(roots_beta.2) >0.80)[1]]``` = -0.135, so 28 cm vs. 13.5 cm

Despite having a different amount of steps, the cumulative sums should lie on the same graph, right? The number of observational nodes shouldn't change the shape of the curves in relation to depth but they do.
```{r}
plot(cumsum(roots_beta), depth, type = 's',
     col = "brown", lwd = 1.5,
     ylab = "soil depth [m]",xlab = "cumsum(relative root density)")
lines(cumsum(roots_beta.2), depth.2, type = 's',
      col = "red", lwd = 1.5)
```

According to the code, the theoretical background is Gale and Grigal (first entry here:  https://tinyurl.com/yd3ggoss ), where the cumulative function Y is given by Y = 1-beta^d with d as depth in cm. But if I add this, it doesn't match either.
```{r}
plot(cumsum(roots_beta), 100*depth, type = 's',
     col = "brown", lwd = 1.5,
     ylab = "soil depth [m]",xlab = "cumsum(relative root density)")
lines(cumsum(roots_beta.2), 100*depth.2, type = 's',
      col = "red", lwd = 1.5)
lines((1-0.97^(seq(0,210,1))),-seq(0,210,1), col = "blue") 
```

Of course, in the function's code creates values for the midpoints in between nodes, but this shape-differences are way too large to be explained by that. Am I missing something here or is there something wrong with the function?
Thanks a lot for your help and for the package in general!
Best regards,
Raphael

**Comment by pschmidtwalter** [comment]
Hi @rhabel!
I adjusted the code, so that the beta-model calculates the root densities for the lower borders of the soil layers (soilnodes), and not anymore for the midpoints. I also omitted normalization, so the sum of root densities will stay below 1. This caused the problems you mentioned. The cumulative root densities at certain depths (with different depth discratizations) are now identical. However, it is correct that relative root densities of single layers will differ, as they depend on the layer thickness. Thinner layers will have a lower root length density.
All the best
Paul
