### ISSUE TITLE
writing output vs returning output comparison.

### ISSUE THREAD

**Issue by trotsiuk** [pschmidtwalter/LWFBrook90R#22]
Hi @pschmidtwalter I wonder If you had a chance to compare the written output and the output directly returned into R in the `r_output` branch.
If yes and everything is ok, I will make my schedule to continue integrating direct output return to R.

**Comment by pschmidtwalter** [comment]
I adjusted the runLWFB90 function to work with your changes, I'll commit & push during the weekend. However I didnt yet check if the directly returned outputs are identical to the .ASC files, but please go ahead. We can check that later.

**Comment by trotsiuk** [comment]
I think it is too early to change the `runLWFB90` as there will be still much of the modifications done regarding input. The main idea was to cross check if the output is correct. Since once I clean the Fortran there will be no written output and to cross check with the written results you would have to switch between branches.

**Comment by pschmidtwalter** [comment]
Okay, I will check output vs files and let you know.

**Comment by pschmidtwalter** [comment]
Hi Vova,
I tested the daily outputs, without the `REW`,  `AWAT`, `ADEF`, and `AWAT40` variables. I also adjusted the `runLWFB90` function to work with direct returns. After rounding, all values are identical, with exceptions only for snowmelt (`smlt`) and soil infiltration (`slfl`). See PDF abov_plots.pdf. However, I think that these differences are somehow related. Maybe, you tapped `smlt `and `slfl `variables at a wrong place and they again get updated before being written to file.
Cheers!

**Comment by trotsiuk** [comment]
Hi Paul,

Thank you for the cross-check. I think the issue is coming form the fact that we have `smlt` and `slfl` twice: one in abovday and one in flowday.
Do we need both of them?

**Comment by trotsiuk** [comment]
HI Paul, 

I have checked the `sml` as well as `slfl` and I fully believe that the issue is only due to rounding (see attached file).

While in the .asc file we have only one digit after coma the value of `0.35` are written as `0.3`. But if you will do it in r `round(0.35, 1) = 0.4`. This is why there is difference in `smlt`. 

I believe I can continue adjusting the code. 

![Screenshot 2020-05-18 at 09 01 12](https://user-images.githubusercontent.com/15097779/82183611-96e96680-98e6-11ea-9220-1b62f0f717d4.png)

![Rplot](https://user-images.githubusercontent.com/15097779/82183711-c0a28d80-98e6-11ea-86a2-35712c2f9668.png)

**Comment by trotsiuk** [comment]
[Output-Vars.xlsx](https://github.com/pschmidtwalter/LWFBrook90R/files/4643184/Output-Vars.xlsx)

**Comment by trotsiuk** [comment]
Hi Paul. I have made the major changes to the fortran code and r_lwfbrook90.
There is still cleaning that need to be done, but this will not affect anything from the main functions. 
I believe you can now easily integrate the r_lwfbrook90 into your routines.

**Comment by trotsiuk** [comment]
Just for your interest, Paul. I also quickly test for speed with and without writing to console. There is even a small difference there, which NO writing being faster.

![Screenshot 2020-05-19 at 12 46 21](https://user-images.githubusercontent.com/15097779/82317669-f1f68880-99ce-11ea-9a38-c6ed05967c73.png)

**Comment by pschmidtwalter** [comment]
Awsome!

**Comment by pschmidtwalter** [comment]
Hi Vova,

I get an error when installing the new version: 

make: *** No rule to make target 'md_decl_const.o', needed by 'md_brook90.o'.  Stop.
ERROR: compilation failed for package 'LWFBrook90R'

**Comment by trotsiuk** [comment]
HI Paul,

HMM, strange. Can you send me the full error during the build.

**Comment by trotsiuk** [comment]
Ah, sorry. I somewhere put the main source files to the gitignore. Now you shall pull and everything shall work

**Comment by pschmidtwalter** [comment]
Hi Vova, 
compilation and installation went smooth. However, the runtime-output is not appearing in the console, instead, the fort.6 file is written again, with output_log = TRUE. The file is locked afterwards, but contains the console feed...

**Comment by trotsiuk** [comment]
hm, that is strange. I wonder if this is rather a windows vs os behaviour? In my case I'm getting such a result
![Screenshot 2020-05-21 at 09 11 43](https://user-images.githubusercontent.com/15097779/82533214-20957000-9b43-11ea-8864-f20a5edb3f84.png)

**Comment by pschmidtwalter** [comment]
This is how it should look like. I'll update to R 4.0 and try again later... I read in "Writing R Extensions" that something with the printing has changed.
Paul

**Comment by pschmidtwalter** [comment]
Hi Vova,
I did some research. It seems that under Windows, the print command has the same effect as the write* command, the output is written to a file. This should be avoided, because it is not portable and will probably be mentioned on a CRAN submission. However, there seem to be some builtin subroutines available to write output to the console: labelpr, dblepr1, realpr1,intpr1.
See https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing
We should try to make them work.

**Comment by trotsiuk** [comment]
Hi Paul, I made few more edits, as suggested in the manual. 
- It shall work well if we are only printing the message (e.g. 'This is the end').
- Unfortunately, it will be hart when printing the intermediate results. There is no option to format the output (e.g. print only first two digits, etc) or insert empty space. Therefore, the output will not look so nice as before. I can suggest either we can round everything to integer or keep as real. I can also try to write the custom 'round' function for fortran, but this also might slows down the printing, which shall be ok, I think. So maybe we print everything with 2 digits after coma?
- Good thing is that now you can use e.g. `capture output` in R and write everything to the object/file. 
- Please let me know if now it works on windows. Please test with `output_log=FALSE`, and then you shall get something as below.

![Screenshot 2020-05-27 at 10 43 33](https://user-images.githubusercontent.com/15097779/82997656-f3dfcd80-a006-11ea-80e1-f0592f477198.png)

**Comment by pschmidtwalter** [comment]
Hi Vova,
good to thear from you, and many thanks for editing!
Concerning your last point, it works under Windows.  I think for the (last) message with the totals it is easiest to simply print 0-digit rounded numbers, or integers.
For intermediate results, it might be an option to concatenate the numbers (rounded to different digits) in one string that then can be printed with, e.g. `subroutine labelpr` or with `intpr`, without actual data.
The hint with the capture ouput function is a good thing, I could then wrap the call to r_lwfbroo90 with `capture.output`, and additionally allow a file-name for the `output`.log argument in my `runLWFB90`-function. I'll try to make this work somehow in the future.

**Comment by trotsiuk** [comment]
Cool!
I'm happy that it worked out. Then I will try to convert the remaining part of the model. I think we still keep the argument `output_log=FALSE/TRUE`, as the preliminary tests above showed that this affect the model speed.
Other option would be to 'print' everything from fortran and capture to 'capture.output', and then the printing will be regulated from R.
But I think the first option is better. Just in case of `error` - Fortran will ALWAYS print the output , e.g. "error due to ....'.

**Comment by pschmidtwalter** [comment]
That sounds perfect. And yes, capturing of the console feed would be done at one level higher, through `runlwfb90`.

**Comment by trotsiuk** [comment]
Pall, can you please make one more test. I wrote the custom function that makes the same string subset as writing. I'm not sure if this will work on windows those. 
Please use `output_log=FALSE`. Ideally you shall get such output

![Screenshot 2020-05-27 at 14 57 48](https://user-images.githubusercontent.com/15097779/83021648-9a899580-a02a-11ea-9e62-aa84976a4f6e.png)

**Comment by pschmidtwalter** [comment]
Looks good:

![grafik](https://user-images.githubusercontent.com/37799585/83042871-6de17800-a042-11ea-8680-1d4215cd69a2.png)

**Comment by trotsiuk** [comment]
COOL! Will finalise the print hopefully tomorrow, and then will be up to you have to integrate everything into R.

**Comment by trotsiuk** [comment]
Hi Pall,
now you shall get all the rest printing with `output_log=TRUE`. Let me know if it works.

Also will be good to test for some errors, if the printing will work out.(e.g. 'matrix psi must be negative or zero')

**Comment by pschmidtwalter** [comment]
Hi @trotsiuk !
I finished developments and pulled the changes into the master. However, I now feel this was a bit too early, becasue I forgot that the precipitation interval is still inactive.
Do you think you we can manage to make it work again soon?

**Comment by trotsiuk** [comment]
Yes, It was "WAYYY' too fast. I was expecting to keep the development branch until it fully tested. 
I'm a bit overload now (also with little one), so don't expect to work much on for the next month.
I would rather suggest to 'revert' merge and keep two branches.

**Comment by pschmidtwalter** [comment]
Ok.  I reverted to v0.3.0 and made up the new dev-branch: dev_directoutput
