### ISSUE TITLE
`MakeRoots.R` tries to pull example from `inst/examples` which does not exist

### ISSUE THREAD

**Issue by rnuske** [pschmidtwalter/LWFBrook90R#31]
The roxygen documentation of `MakeRelRootDens()` tries to pull its example from `inst/examples/MakeRelRootDens-help.R` but this files does not exist.

**Comment by rnuske** [comment]
The current man-page still shows an old example. So the example might be rescued from `LWFBrook90R/man/MakeRelRootDens.Rd` and then the documentation updated.

**Comment by pschmidtwalter** [comment]
This was already solved before the big merge of your contribution 'switching the entire parallel computing approach'.
