### ISSUE TITLE
`runLWFB90()` is very chatty

### ISSUE THREAD

**Issue by rnuske** [pschmidtwalter/LWFBrook90R#33]
There is lots of text output to stdout / R console by `runLWFB90()` when called by `msiterunLWFB90()` or `mrunLWFB90()`.

It might be a good idea to supress the messages or advise the user to shut up `runLWFB90()` with `verbose=FALSE`. Another option might be to have multiple verbosity levels: one with many messages if run on its own, one with few messages if run by  msiterunLWFB90() or mrunLWFB90() and one without any messages.

**Comment by rnuske** [comment]
Verbosity got worse!

Now also fortran code writes to stdout and does not respect `verbose=FALSE`.

**Comment by pschmidtwalter** [comment]
This is the feed that formerly went to Log.txt, or also the console. You have to set `output.log = FALSE` to suppress Fortran's stdout.  
I have several ideas to shut up stdout or redirect to a file, using capture_output. 
Will be the next thing to work on.
For now, carry on by using `output.log = FALSE` and `verbose = FALSE` in `runLWFB90`!

**Comment by rnuske** [comment]
might be worth to look at logging options such as [lgr](https://cran.r-project.org/web/packages/lgr), [logger](https://cran.r-project.org/web/packages/logger/), [log4r](https://cran.r-project.org/web/packages/log4r/) and the older [logging](https://cran.r-project.org/web/packages/logging/)

**Comment by pschmidtwalter** [comment]
Verbosity was reduced by disabling Runtime-Output from Fortran, only messages are printed to the console, if `verbose = T` (the new default).
Also, Fortran does not write to stdout anymore (#39).
