### ISSUE TITLE
Fortran writes to stdout

### ISSUE THREAD

**Issue by rnuske** [pschmidtwalter/LWFBrook90R#39]
R CMD check note:

```
File ‘LWFBrook90R/libs/LWFBrook90R.so’:
  Found ‘_gfortran_st_write’, possibly from ‘write’ (Fortran), ‘print’
    (Fortran)
    Object: ‘md_brook90.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

**Comment by pschmidtwalter** [comment]
Hi @trotsiuk ! 
Can you take care of this? 
It prolly originates from your makeString function in md_brook90.f95, line 784.

**Comment by trotsiuk** [comment]
HI @pschmidtwalter 

Unfortunately I don't see other solution how to reformat everything before outputting to the console. 
while we using `intpr` to write into console, we shall preformat it in some way. 

I can't find a solution now. I guess the easiest is simply to remove the writing to console.

**Comment by trotsiuk** [comment]
we can skip the preformating, but the output will look with many decimals its

https://github.com/pschmidtwalter/LWFBrook90R/issues/22#issuecomment-634518939

or one need to write a specific function for each of the value

**Comment by pschmidtwalter** [comment]
I see. Could you maybe write an example function for reformatting one of the variables? I could then adapt for the other values.

**Comment by pschmidtwalter** [comment]
I think it is not really worth to put more effort in the formatting of runtime-console-output, and just shut down the printing. This would go in favour of the verbosity issue #33 and makes evyrthing easier. 

We need however to think about the signalling of errors, to make sure the user can trace back possible problems. My idea would be to attach an integer to the list of returns, that we can then interprete inside R. Anywhere the `error`-variable in md_brook90.f95 is set to `.true.`, a message is currently printed and the day loop should be stopped by `go to 999`. We can skip the printing of the message and instead return an integer code that we interprete in R, with 0 being returned when the simulation went through smoothly and the message was "THAT IS THE END".

**Comment by trotsiuk** [comment]
I think the idea behind the log/output is to show user what cause the error (e.g. convergence, etc). If we only give ERROR, there will be no possibility to identify what caused the error. 

Potentially one can list all possible errors, and code them by integer as you suggested.

**Comment by pschmidtwalter** [comment]
Exactly. We could then interprete it in R like:

- 0: "THAT IS THE END" (line 772), everything ok
- 1: "FWETK: slope is zero, stopping programm!" (line 3133), raise **warning** in R
- 2: "FWETK: no convergence, stopping programm!" (line 3119),  raise **warning** in R
- 3: "Soil parameter combination error" (line 770), raise **error** in R
- 4: "matrix psi must be negative or zero" (lines 1956, 1988), raise **error** in R
- 5: "SWATI < 0 or SWATI > (SWATMX, (swchek.h),  raise **error** in R
- 6: "Date error" (line 173),  raise **error** in R

**Comment by pschmidtwalter** [comment]
Error codes are now returned as integer, and interpreted in R. As Fortran is not writing to stdout anymore, and R CMD check passes without Notes/Warnings/Errors.
