### ISSUE TITLE
texture classification in PTF HYPRES

### ISSUE THREAD

**Issue by rhabel** [pschmidtwalter/LWFBrook90R#51]
The equations in hydpar_hypres are identical (given the change in the order of magnitude due to different units) to the equations in Woesten et al (1999). However, according to the paper, HYPRES was developed with a 2-50 μm silt-range. The other two PTFs PTFPUH2 and WESSOLEK use a 2-63μm silt range. So far, there is no correction for that implemented, is that correct? 

For example, the package "soiltexture" provides a correction for different texture classes:
```{r}
test <- data.frame("CLAY" = c(5,60,15,5,25), "SILT" = c(5,8,15,25,65), "SAND" = c(90, 32, 70, 70, 10))
soiltexture::TT.text.transf(tri.data = test, base.css.ps.lim = c(0,2,50,2000), dat.css.ps.lim = c(0,2,63,2000))
```

For large silt-percentages this makes quite a difference. Wouldn't it be good to implement such a correction into hydpar_hypres?

**Comment by pschmidtwalter** [comment]
I think this can be seen a preprocessing step and should be done outside LWFBrook90R. Nevertheless, I updated the documentation for the function, mentioning the particle size limits for clay, silt, sand.
Thanks!
