### ISSUE TITLE
Calculation of AWC using PTF-functions

### ISSUE THREAD

**Issue by acmue** [pschmidtwalter/LWFBrook90R#52]
I calculated the AWC from retention curves that were derived from the PTFs HYPRES, Wessolek and PTFPUH2. While the results of Wessolek and PTFPUH2 were similar, HYPRES led to twice as high AWCs. As I ran the same code on the MvG-parameters and the effect is reproducible in other areas, I assume there might be an issue with the HYPRES PTF.

**Comment by pschmidtwalter** [comment]
Hi Ann-Christin,
can you provide some sample data (a few soil profiles) and the R-Code you used to calculate AWC?
Makes it easier to find the issue.
Regards
Paul

**Comment by pschmidtwalter** [comment]
Dear Ann-Christin,
When using pedotransfer functions, it is important to critically check the ranges of input parameters. It sometimes happens that PTFs produce weird results, when provided input parameter ranges or combinations thereof largely exceed the ranges of the data that were used to develop a PTF. Such extrapolations then sometimes do not make sense. In your case, it might be that horizons with low clay contents and very low bulk densities are responsible for bad AWC values.
Regards
Paul
