### ISSUE TITLE
CRAN LTO issue

### ISSUE THREAD

**Issue by pschmidtwalter** [pschmidtwalter/LWFBrook90R#58]
CRAN checks gave the following issues with link time optimization
(https://www.stats.ox.ac.uk/pub/bdr/LTO/LWFBrook90R.out)

1)
> gfortran -fno-optimize-sibling-calls  -fpic  -g -O2 -mtune=native -Wall -pedantic -flto=10 -c  md_brook90.f95 -o md_brook90.o
> VARDCL.h:174:28:
> 
>   174 | real(kind=8) :: Par(MPar,ML)    ! hydraulic parameters for layer
>       |                            1
> **Warning**: Array ‘par’ at (1) is larger than limit set by ‘-fmax-stack-var-size=’, moved from stack to static storage. This makes the procedure unsafe when called recursively, or concurrently from multiple threads. Consider using ‘-frecursive’, or increase the ‘-fmax-stack-var-size=’ limit, or change the code to use an ALLOCATABLE array. [-Wsurprising]

2) 
> skeleton.c:7:6: **warning**: type of ‘s_brook90_f_’ does not match original declaration [-Wlto-type-mismatch]
>     7 | void F77_NAME(s_brook90_f)(double *siteparam, double *climveg, double *param, double *pdur,
>       |      ^
In line 9, `pr` is defined as `int`, but in 's_brook90_f_'  `pr` is logical

3)
> md_brook90.f95:33:22: **note**: ‘s_brook90_f’ was previously declared here
>    33 | subroutine s_brook90_f( siteparam, climveg, param, pdur, soil_materials, soil_nodes, precdat, &
>       |                      ^
> md_brook90.f95:33:22: **note**: code may be misoptimized unless ‘-fno-strict-aliasing’ is used

Not sure, do we also have to fix the **notes**, or only **warnings**?
I dont know also how to check if attempts to fix were successful.

**Comment by trotsiuk** [comment]
Hi @pschmidtwalter 

1. This seems to be kind of recent bug in compiler [some info](https://stackoverflow.com/questions/65384213/using-very-large-arrays-in-fortran-gfortran/65391732#65391732), but I can make the array allocatable as suggested [here](https://www.scivision.dev/gfortran-stack-to-static-warning/)

2. Is the new commit #57 changed something?

3. This a bit strange, I still not sure what is the reason.

I wonder if you can test check CRAN with [`Link-Time Optimization`](https://cran.r-project.org/doc/manuals/r-devel/R-admin.html#Link_002dTime-Optimization)

**Comment by trotsiuk** [comment]
For the issue:

2. try to change the `logical` to `INTEGER` on `L32` (for both pr and timer)

**Comment by trotsiuk** [comment]
For the issue:

1. currently `ML = 1000` declared in `line 17` of `vardcl.h`. I wonder if we really need up to `1000` layers, or this simply can be reduced to 100 or 500? This can remove the first issue.

**Comment by pschmidtwalter** [comment]
`ML = 100` is definitely enough.
I will 
> 2. try to change the `logical` to `INTEGER` on L32 (for both `pr` and `timer`)
You do the rest? 
I will also try to find a way to check with LTO option...
Thanks!

**Comment by trotsiuk** [comment]
If you will be doing the `ML`, so please directly change the `logical to integer` on[ `L32`](https://github.com/pschmidtwalter/LWFBrook90R/blob/4d2c3a539e9af2d2177efaf5aa809eed46fc4081/src/skeleton.c#L32).

It will compile, I have tested. But please check if it will pass other tests.

For the `issue 3` I'm still not sure. I wonder if this is simply just because line is too ling?

**Comment by trotsiuk** [comment]
@pschmidtwalter I was asking only to change the L32 for the issue 2. I was thinking that this will be taken by fortran in the correct way then. But I saw that you did the full change in The Fortran code with your commit.

I wonder if simply changes the L32 didn't worked or you decided to do that way particularly?

**Comment by pschmidtwalter** [comment]
I had to change it also in the Fortran code... it was not compiling, because `if (pr) then..` is expecting a logical.

**Comment by trotsiuk** [comment]
ok, strange. Because it was compiling well on my machine.

**Comment by trotsiuk** [comment]
So the branch [issue_58_logival_integer](https://github.com/pschmidtwalter/LWFBrook90R/tree/issue_58_logical_integer) will not compile for you?

**Comment by rnuske** [comment]
The [README.txt](https://www.stats.ox.ac.uk/pub/bdr/LTO/README.txt) in the ftp directory where the LTO issue is reported describes how the LTO compilation was carried out and might help to reproduce the error locally / check the fixes.

**Comment by pschmidtwalter** [comment]
Thanks Robert!
I'll try to today to get it running... 

> So the branch issue_58_logical_integer will not compile for you?
Yes, @trotsiuk, it compiles... dont know what went wrong before.

**Comment by pschmidtwalter** [comment]
I managed to test with LTO using Docker "rhub/debian-gcc-devel-lto" with the following results:

- The check reproduced the installation warning of version 0.4.3, but without the warning No. 1 about  the `ML = 1000`... is Ripley's warning really a bug and can we leave it as it is?
- In Vova's branch [issue_58_logical_integer](https://github.com/pschmidtwalter/LWFBrook90R/tree/issue_58_logical_integer) the warnings persist...
- With my branch [fix-lto](https://github.com/pschmidtwalter/LWFBrook90R/tree/fix-lto) all warnings disappeared.

So, the solution seems to be to declare `pr` and `timer` as integer(kind = c_int) all the way... Maybe there is an easier way?

**Comment by trotsiuk** [comment]
Maybe not the most elegant solution would be to:

- pass `pr_int` and `timer_int` as integers to fortran
- in fortran after declaration, run something line:
```
if ( pr_int .eq. 1) then
pr = .TRUE.
end if

```

In this case there will be no need to change the fortran code

**Comment by trotsiuk** [comment]
Hi @pschmidtwalter I have now did the allocation. However, only to the main part, not to the other subroutines where sometimes PAR is called. Please check the `LTO` and let me know shall it work now.

**Comment by pschmidtwalter** [comment]
Thanks!
The test passed, however, my local LTO test could not reproduce the original warning associated with `Par()` so we cant really know if attempts were successful. I will mention that in the comments.
Did you check the simulation speed? Are there differences?
All the best
I will merge and resubmit tomorrow
Paul
