### ISSUE TITLE
Typo in wessolek_mvg_tab10

### ISSUE THREAD

**Issue by MichaKoe** [pschmidtwalter/LWFBrook90R#60]
Hi Paul ... 

Typo in table "wessolek_mvg_tab10" used by "hydpar_wessolek_tab":

The texture class abbreviations "mSfS" (with capital "S" at the end) should be changed to"mSfs" in order to correspond to the nomenclature of the German soil mapping instructions. Otherwise NA is created when using soil data with standard texture class abbreviations and a coulple of below ground processes cannot be calculated. 

Greetz!

**Comment by pschmidtwalter** [comment]
Yes! This was fixed in a previous commit, please install the development version!
Thanks
