### ISSUE TITLE
aggregation auf model outputs with "process_outputs_LWFB90"

### ISSUE THREAD

**Issue by MichaKoe** [pschmidtwalter/LWFBrook90R#67]
Hi Paul and happy new year,

I was checking the results of  the “process_outputs_LWFB90” function today and I found a problem when aggregating "budg" for “Ann” and "Mon” periods. 

Here the aggregated tables still have 365 rows per year instead of 1 for annual or 12 for montly aggregation. I think the reason is that you aggregate values by groups (yr, mo ... ) using “sum” ( prec, flow, evap, seep) while using “rowid” to extract the last entry per group for other variables (e.g. snow, swat, gwat) in the same data.table call, where you intend to store the last value of the given period. 

I suppose e.g. line 217 of your code (and all the similar lines) should read:

`swat = round(last(swat),1),` 
or
`swat =  round(swat[.N],1),`

instead of 

`swat = round(swat [rowid(yr, doy) == prec_interval],1),` 

to  always get the last value per group. 

Best regards,

Micha

**Comment by pschmidtwalter** [comment]
Thanks!
